### ISSUE TITLE
Kollision und Highscore!!!!!

### ISSUE THREAD

**Issue by DarioScarpello** [julianochsenreiter/self-learning-ai-itp#3]
**Kollision von Raumschiff ist abgrundtief schlecht!!!!!**
Aus irgendeinem Grund gibt es nur einen Punkt im Raumschiff der auch wirklich als Raumschiff zählt, dass führt dazu, dass das Raumschiff zur Hälfte in einem Hindernis stecken kann und es trotzdem nicht zerstört wird!

**Highscore ist beim Download schon auf 19**
Voller Vorfreunde downloadete ich das Spiel A.I.M und musste mit entsetzen feststellen, dass der Highscore schon auf 19 liegt!! Dadurch wurde meine Privatsphäre stark verletzt!!

**Comment by qualitykk** [comment]
Alles gefixt bruder

**Comment by DarioScarpello** [comment]
Vielen Dank jetzt kann ich SLAIM endlich genießen!!!!!
