### ISSUE TITLE
Tolles Repository

### ISSUE THREAD

**Issue by JovanoMat** [julianochsenreiter/self-learning-ai-itp#4]
Diese Projekt ist super toll! ### Hallo ### **Tolles Projekt** 

> Es ist so toll
> Man kann spielen flappy `bird`

- > Ich hab das gemoddet

- [x] Macht bitte A.I. self Learning [S.L.A.I.M. (Self Learning AI Minigame)]

**Comment by qualitykk** [comment]
gemacht 💪🏻
