### ISSUE TITLE
Meine Review für julianochsenreiter / self-learning-ai-itp

### ISSUE THREAD

**Issue by RoederFer** [julianochsenreiter/self-learning-ai-itp#5]
**---{ Graphics }---**
☑ You forget what reality is
☐ Beautiful
☐ Good
☐ Decent
☐ Bad
☐ Don‘t look too long at it
☐ MS-DOS

**---{ Gameplay }---**
☑ Very good
☐ Good
☐ It's just gameplay
☐ Mehh
☐ Watch paint dry instead
☐ Just don't

**---{ Audio }---**
☐ Eargasm
☐ Very good
☐ Good
☐ Not too bad
☐ Bad
☑ I'm now deaf

**---{ Audience }---**
☑ Kids
☑ Teens
☑ Adults
☑ Grandma

**---{ PC Requirements }---**
☑ Check if you can run paint
☐ Potato
☐ Decent
☐ Fast
☐ Rich boi
☐ Ask NASA if they have a spare computer

**---{ Difficulty }---**
☐ Just press 'W'
☐ Easy
☑ Easy to learn / Hard to master
☐ Significant brain usage
☐ Difficult
☐ Dark Souls

**---{ Grind }---**
☐ Nothing to grind
☑ Only if u care about leaderboards/ranks
☐ Isn't necessary to progress
☐ Average grind level
☐ Too much grind
☐ You'll need a second life for grinding

**---{ Story }---**
☑ No Story
☐ Some lore
☐ Average
☐ Good
☐ Lovely
☐ It'll replace your life

**---{ Game Time }---**
☐ Long enough for a cup of coffee
☐ Short
☐ Average
☐ Long
☑ To infinity and beyond

**---{ Price }---**
☑ It's free!
☐ Worth the price
☐ If it's on sale
☐ If u have some spare money left
☐ Not recommended
☐ You could also just burn your money

---{ Bugs }---
☐ Never heard of
☐ Minor bugs
☐ Can get annoying
☐ ARK: Survival Evolved
☑ The game itself is a big terrarium for bugs

**---{ ? / 10 }---**
☐ 1
☐ 2
☐ 3
☐ 4
☐ 5
☐ 6
☑ 7
☐ 8
☐ 9
☐ 10

**Comment by qualitykk** [comment]
du profi
